---
- hosts: all
  become: yes
  vars_files:
  - testbed_vars.yml
  tasks:
  - import_tasks: testbed_helper.yml
    vars:
      boot_script: pi-boot.j2
  - template: src=fakepi-default-route.j2 dest=/fakepi-default-route owner=root mode=a=r
